### PR TITLE
Fix: json api reducer - delete request

### LINKED ISSUE #66: Validate if JsonApiReducer removes all entities on Delete
https://github.com/bornfight/aardvark/blob/master/src/reducers/JsonApiReducer.ts#L83

### PR DESCRIPTION
**Pull request by JuraJuki**
~~- delete request now returns current state data instead of a reset.~~
- delete requests removes item from state and returns it

Fixes #66

### CODE REVIEW

File: src/reducers/JsonApiReducer.ts [hunk 1]
```diff
@@ -136,6 +143,28 @@ export class JsonApiReducer {
...
+
+        // Removes the request-deleted item from object of objects extracted above
+        // @ts-ignore
+        const { [idToDelete]: removedValue, ...childWithout } = parentValue;
+
+        // Merge back together
+        return {
+            ...noChild,
+            [keyToDelete]: childWithout,
+        };
```
Comment (renatoruk) [inline src/reducers/JsonApiReducer.ts:165]: Looks nice!

I'd suggest a minor improvement in naming so it's easier to understand on the last return what actually happened. 
Also, fixed ts ignore with casting to the required type. It was necessary because it could not index type "undefined", which was a possible scenario. That should return initial state.

```suggestion
// endpoint is of the following format: "/cars/2"
        const resourceType = endpoint.split("/")[1];
        const recordId = endpoint.split("/")[2];
        const {
            [resourceType]: targetResource,
            ...entitiesWithoutTargetResource
        } = entities;

        /**
         * nothing to delete, returning initial state
         */
        if (targetResource && targetResource[recordId] === undefined) {
            return entities;
        }

        // Removes the request-deleted item from object of objects extracted above
        const {
            [recordId]: removedValue,
            ...targetResourceWithoutDeletedKey
            // casting to identifiers because of the check for undefined in the earlier conditional
        } = targetResource as Identifiers;

        // Merge back together
        return {
            ...entitiesWithoutTargetResource,
            [resourceType]: targetResourceWithoutDeletedKey,
        };
```

**Review by renatoruk — COMMENTED** [review]
Looks good, nice fix! Check only my comment
