### PR TITLE
Fix: nested attributes {}

### LINKED ISSUE #72: Attributes {}
- Relationship of relationship which is an array of objects. Those objects can have attributes {}

### PR DESCRIPTION
**Pull request by JuraJuki**
~~#**WIP**~~

- adds a test for checking of attributes:{} existance for relationship's relationship when both are array of objects
- fixes https://github.com/bornfight/aardvark/issues/72

### CODE REVIEW

**Comment by renatoruk** [comment]
@JuraJuki What is the status of this PR?

**Comment by JuraJuki** [comment]
> @JuraJuki What is the status of this PR?

The current status of it, is that I need to discuss with you about it. Testing it is a bit of a problem because of nested data..the console would not write the differences. Other than that, I'm not sure why is it happening...Why does attributes:{}  show up again

**Comment by JuraJuki** [comment]
We agreed upon the frontend team to do the work for this in a short debate with Matteo and Renato. The attributes: {} is unnecessary here, it is not breaking but it would be better off without it

**Comment by renatoruk** [comment]
We could probably remove attributes somewhere here https://github.com/bornfight/aardvark/blob/master/src/json-api-client/JsonaDataFormatter.ts#L102

@JuraJuki

**Comment by JuraJuki** [comment]
@renatoruk I think this should be the proper fix, mind taking a look? I'm not sure how to test this since tests do not print this deep. Other than that it is kinda odd that tests (when logged in a console) show only id and type keys on the object. But clearly on the example it shows that it is not true.

File: src/json-api-client/JsonaDataFormatter.ts [hunk 1]
```diff
@@ -111,10 +115,56 @@ class JsonaDataFormatter {
...
             entity.attributes = undefined;
         }
+        let relationshipsWithoutAttributes;
+        if (entity.relationships) {
+            const relationships = entity.relationships;
+            relationshipsWithoutAttributes = this.removeAttributesFromRelationships(
+                relationships,
+            );
+            entity.relationships = relationshipsWithoutAttributes;
+        }
```
Comment (renatoruk) [inline src/json-api-client/JsonaDataFormatter.ts:125]: This looks nice, but I think this might be better placed in its own function and called somewhere else. 
Reason behind this is because the method is called "removeClientGeneratedEntityFlag" and with this addition it definitely does a bit more than that.

Maybe this logic should be in separate function called something like `getEntityWithoutRelationshipAttributes`. 

Bear in mind that `removeClientGeneratedEntityFlag` and this new function should be called in tandem in certain places so a third function that wraps those to might be necessary to commit all those operations.

**Review by renatoruk — COMMENTED** [review]
I like the idea, but there is still some work to be done. Keep it up!

**Comment by renatoruk** [comment]
Cool! Awesome that you've updated the docs. Mind taking a look why the coverage fell? It should be available by going to codecov detail report
